### ISSUE TITLE
[BUG] Renamed instances don't show in wsl --list

### ISSUE THREAD

**Issue by thawkins** [bostrot/wsl2-distro-manager#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you rename an instance, and then execute "wsl --list" the new name is not shown, only the old name.

This is particularly difficult if you want to create clones of the same distro instance for testing using the Commandline, plus the distroname is used when addressing the files in the "linux files" action. 

### Expected Behavior

distro instance is renamed both in the ui and in the underlying WSL system

### Steps To Reproduce

1. install wsl
2. execute "wsl --install Ubuntu-22.04
3. // Rename created distrol instance in UI
4. execute "wsl --list" 
5. Old name is shown

### Environment

```markdown
- Windows Version: windows 
Edition	Windows 11 Pro
Version	22H2
Installed on	‎18/‎02/‎2023
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

- WSL Distro Manager Version: 1.6.0

- WSL Version:
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1265

- Source:
```

**Comment by bostrot** [comment]
That is intended as renaming in wsl does not work and would need to be done by re-importing the distro.

Earlier versions of this renamed distros by exporting/importing with a different name but that created some other issues.
