### ISSUE TITLE
[BUG] Distro auto-completion list (add) not usable

### ISSUE THREAD

**Issue by xasx** [bostrot/wsl2-distro-manager#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use an Eyetracker to control my computer. Mouse behavior is a bit different and you usually need more steps to do things, thus need more time.

When I want to get a list of supported distros in the add instance dialog, it disappears immediately as soon as the mouse is not in the area of the list. Scrolling the list is not possible at all.

To complicate interaction further, the focus is automatically drawn from the respective text box that makes it hard to type anything in there.

### Expected Behavior

The list shows up and stays open until a selection is made so one can look through all distros.
Furthermore, a usable scroll bar is shown.
The focus stays in the respective text box.

### Steps To Reproduce

1. Without an Eyetracker, it might need some emulating behavior to reproduce 
2. just install the software 
3. run it and try adding a distro
4. in the rootfs text box, click to geht the list of built-in distros 
5. move the cursor out (just guessing what would emulate the Eyetracker)
6. see

### Environment

```markdown
- Windows Version: 11 Pro • 10.0.22621.1343
- WSL Distro Manager Version: 1.6.0
- WSL Version: 1.1.3.0
- Source: Windows Store
```

### Anything else?

It would be great if the distro list was a real drop down menu.

**Comment by bostrot** [comment]
Thanks for reporting that!

I am wondering, could you check if that also hapoens with v1.5?

If fhat works better then this probably has something to do with https://github.com/bdlukaa/fluent_ui/issues/698.
