### ISSUE TITLE
[FEATURE] Delete Confirmation

### ISSUE THREAD

**Issue by frizzant** [bostrot/wsl2-distro-manager#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem?

I have a main Distribution I use for most of my tasks. From time to time I use another WSL distro for other non related tasks.
What I have noticed is, that the "delete" button does not ask for confirmation.

While I do backups, this would be a small but relevant feature to ensure I don't accidentally delete something I actually needed.

![image](https://user-images.githubusercontent.com/16461486/225040581-dc7908ad-ea0b-4a01-90c8-bda682ac585e.png)

### Solution

Add second confirmation popup.

### Alternatives

Hide this action by default

**Comment by bostrot** [comment]
Closing this for now. Feel free to reopen if that is not what you meant.
