### ISSUE TITLE
Cloning a distribution is getting stuck on copying

### ISSUE THREAD

**Issue by hedwiggggg** [bostrot/wsl2-distro-manager#11]
**Describe the bug**
When I try to clone a distribution, the message "Copying [...]. This might take a while..." and won't go away. If I restart the WSL Manager, both distributions are there and can be used.

**To Reproduce**
1. Download WSL Manager
2. Create a distribution (used `focal-server-cloudimg-amd64-wsl.rootfs.tar.gz`, with default save location and specified a default user)
3. Try to clone the distribution 

**Expected behavior**
After the cloning process, the alert should disappear and the manager should be usable again.

**Screenshots**
<img width="492" alt="image" src="https://user-images.githubusercontent.com/42947316/150555969-dd85930e-339a-4237-92cf-d95206bbeb30.png">

**Desktop:**
 - OS: Windows 11 Pro 10.0.22000 Build 22000
 - Version: v0.7.1
 - Source: GitHub releases

**Comment by bostrot** [comment]
How long have you waited for the process to be done?

**Comment by bostrot** [comment]
Should be fixed with commit 41e2d52.
