### ISSUE TITLE
[BUG] zh-tw language doesn't display in zh-TW locale on Windows

### ISSUE THREAD

**Issue by yrctw** [bostrot/wsl2-distro-manager#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `zh-tw` language file is not applied in `zh-TW` locale on Windows.
Still showing with `zh` language file.
Also there is no manual language setting avaliable.
This issue can be solved when replacing the `data\flutter_assets\lib\i18n\zh.json` with `data\flutter_assets\lib\i18n\zh-tw.json`

### Expected Behavior

Should be show in the same locale of the system environment.

### Steps To Reproduce

1. Boot a Windows 11 in zh-TW locale.
2. Open the app.

### Environment

```markdown
- Windows Version: Windows 11 Pro Insider Preview Build 25314
- WSL Distro Manager Version: v 1.6.1
- WSL Version: v1.1.3.0
- Source: GitHub releases
```

**Comment by bostrot** [comment]
Can you check if this fixes it: https://github.com/bostrot/wsl2-distro-manager/suites/11718091473/artifacts/609895083

**Comment by yrctw** [comment]
> Can you check if this fixes it: https://github.com/bostrot/wsl2-distro-manager/suites/11718091473/artifacts/609895083

It still showing with `zh` language file.

**Comment by bostrot** [comment]
Weird. Could you post the output of following PowerShell command: `Get-WinUserLanguageList`

**Comment by yrctw** [comment]
> Weird. Could you post the output of following PowerShell command: `Get-WinUserLanguageList`
```
LanguageTag     : zh-Hant-TW
Autonym         : 中文(台灣)
EnglishName     : Chinese
LocalizedName   : 中文 (繁體，台灣)
ScriptName      : 中文 (繁體)
InputMethodTips : {0404:{D9012138-88BF-46F4-B599-E69D8BA2FED6}{2939307A-285F-47F9-B909-8089DF8A7FDD}}
Spellchecking   : True
Handwriting     : True
```
It should be `zh-Hant-TW`

**Comment by bostrot** [comment]
Can you check if the current build works for you? https://github.com/bostrot/wsl2-distro-manager/suites/11753521150/artifacts/612514822

**Comment by bostrot** [comment]
My bad. This should do the trick: https://github.com/bostrot/wsl2-distro-manager/suites/11758130834/artifacts/612835298

If it doesn't tell me what tag it outputs in the bottom status message.

**Comment by yrctw** [comment]
> How about this one? https://github.com/bostrot/wsl2-distro-manager/suites/11763654773/artifacts/613224013
It's works now. Thank you very much!
![image](https://user-images.githubusercontent.com/21277100/227264531-16bda8ad-44c5-4350-b830-fea173261098.png)
