### ISSUE TITLE
Copying a distro does not work

### ISSUE THREAD

**Issue by SaeidYazdani** [bostrot/wsl2-distro-manager#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I click on copy and give a new name. Nothing happens. I just get a notification that copy was done, but nothing happened actually 

### Environment

```markdown
- Windows Version: 11
- WSL Distro Manager Version: 1.6.2
- WSL Version: 2
- Source:
```

**Comment by bostrot** [comment]
Do you have any special characters in the names?

**Comment by bostrot** [comment]
I just created a build with extra logging. Can you try it again here? It should report back any errors (hopefully):

https://github.com/bostrot/wsl2-distro-manager/suites/12259396937/artifacts/648996275

**Comment by SaeidYazdani** [comment]
Hi, I updated the app using windows store, and ater replicating the possible "bug" I clicked on send log data

**Comment by SaeidYazdani** [comment]
I tried this one but says access is denied. Also my security really doesn't allow unsigned stuff.

was there anything usefull in the log file? I found the logfile somewhere in the AppData\Local\Packages\9891PhantomDevs.WSL2Manager_rqq3vyma0b55r\LocalCache\Roaming\com.bostrot\WSL Distro Manager and it just has a header line only:

WSL Manager v1.7.3 on windows "Windows 10 Pro" 10.0 (Build 22621)

============================================================

**Comment by bostrot** [comment]
Unfortunately, this was all :/
Only errors get logged for now (will change that in the future).

But I have a strong feeling this might be related to #134 so that build might fix it. Could you check if there is a second log file here? `%appdata%\com.bostrot\WSL Distro Manager`

**Comment by SaeidYazdani** [comment]
Well the nighly build has no log either.

So this is basically what I do:

I have a folder that has some distros (I registred them manually with wsl.exe) but WSL Manager identifies them and works fine.

When I try to copy one, nothing happens, it just says success...
I have uploaded images here
https://ufile.io/35903rbl

**Comment by bostrot** [comment]
Ok, I found a promising issue and fixed it [here](https://github.com/bostrot/wsl2-distro-manager/suites/12290414538/artifacts/651172449). Can you test it?

**Comment by SaeidYazdani** [comment]
well thanks but as I said it gives "access denied" ... I think it only works if it is updated through windows store.

**Comment by bostrot** [comment]
Isee. I submitted a build to the store anyways. It will take a couple of days until it is available, though.

**Comment by bostrot** [comment]
Does the error log say anything at least?

**Comment by SaeidYazdani** [comment]
Hi, I might have found some clues.

- Sadly the log data is not being generated anymore (I searched for "*wslmanager*" in my C drive an nothing was found).
- My WSL folders are NOT in C drive (I have all my WSL images in F:\WSL-IMAGES  e.g. F:\WSL-IMAGES\ubuntu-dev )
- When I click on copy, the app will create a folder with the name given in the textbox in the ROOT folder of C. This folder will be empty after the app shows success message
- so lets say I want a copy of  'F:\WSL-IMAGES\ubuntu-dev' and give a name 'mycopy' then I expect it to be generated in  F:\WSL-IMAGES\mycopy

**Comment by SaeidYazdani** [comment]
I just tried 1.8.0 … still does not work

As I said, my WSL files is in F drive but the app creates folders for the copy in C drive.
but regardless, the app creates the correct folder structure it seems.
The created folders in C drive are still empty after success message.

all it needs to do is to copy 'ext4.vhdx' file from the source folder to target folder in the right drive under the right name. I don't get it why it is not working :D

**Comment by SaeidYazdani** [comment]
I tried 1.8.3 right now and still the same problem.

Now I uninstalled and reinstalled, hoping maybe some cached values are causing this, but no :(
What is the "Default Distro Location" means at all? I wan all of my distros be in a single path.
Again, when I try to copy a wsl image wichi is in F:\WSL-IMAGES, the app creates C:\WSL-IMAGES
Why doesn't it respect that option?

Also, is there a possibility to "import" already registered wsl images (which were created using 'wsl' --import or --import-in-place commands?

One last request...can you tell me where in your source code is responsible for copying? sadly I have no idea about flutter otherwise I would have a look...
![image](https://user-images.githubusercontent.com/6137136/234712177-ba26fae9-573a-4edb-9f2c-ed8d4adbb1fd.png)

**Comment by bostrot** [comment]
Weird, for me it respects that option. 

1.8.3 just fixed a logging bug. I have one more idea I wanna try to reproduce the issue you are having. I'll try that tomorrow. The default distro path should be the path where the distros are saved. As the name suggests.

Also can you try one more thing: there is a "shared_preferences.json" file in appdata/com.bostrot/wsl distro manager. Can you try renaming that (e.g. to shared_preferences.json.bak) restart the app and check if that changes anything? This file is not deleted when uninstalling (probably should change that).

In the source code copying is in the api/wsl.dart file under the copy function.
