### ISSUE TITLE
Add `/etc/wsl.conf` on distro creation, if default user is specified

### ISSUE THREAD

**Issue by hedwiggggg** [bostrot/wsl2-distro-manager#12]
**Is your feature request related to a problem? Please describe.**
When I create a new distro with a default user specified, it doesn't create the `/etc/wsl.conf`. If I open the distro through the commandline or if I use `code [folder]` to open vscode with wsl integration, it's always starting as root.

**Describe the solution you'd like**
Would be nice to also generate a `/etc/wsl.conf` where the default user is set.
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user-settings

**Comment by bostrot** [comment]
This is added with commit c1ef2d7.
