### ISSUE TITLE
[BUG] `writingtodisk-text` when installing a Docker image

### ISSUE THREAD

**Issue by ZzZombo** [bostrot/wsl2-distro-manager#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This text appears briefly towards the end as a status update.

### Expected Behavior

Localized message appears instead.

### Steps To Reproduce

1. Attempt to install `dockerhub:archlinux:latest`.
2. Wait for progress to reach this stage.

### Environment

```markdown
- Windows Version: Windows 10.
- WSL Distro Manager Version: v1.7.2.
- WSL Version: 2.
- Source: `scoop`.
```

**Comment by bostrot** [comment]
What is your language code?
