### ISSUE TITLE
[BUG] Docker images never finish installation

### ISSUE THREAD

**Issue by ZzZombo** [bostrot/wsl2-distro-manager#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It gets stuck during the second appearance of the "Creating instance..." message. Resource monitoring reveals the app does nothing, no network or disk access is done.

### Expected Behavior

Installation finishes successfully.

### Steps To Reproduce

1. Install `dockerhub:archlinux:latest`.
2. Wait for the text "Creating instance..." to appear the second time. It hangs here.

### Environment

```markdown
- Windows Version: Windows 10.0.19045.2728.
- WSL Distro Manager Version: v1.7.2.
- WSL Version: 1.2.0.0.
- Source: `scoop`.
```

### Anything else?

It got stuck for 2 hours at this point and counting.

**Comment by bostrot** [comment]
Does this also happen with other images for you?

E.g. alpine:latest

**Comment by bostrot** [comment]
I just tested it, and it works for me. Took about 2 minutes for the whole process. It could have something to do with the fact that you are running Windows 10. Would you happen to have a Win 11 machine to test this on? 

![image](https://user-images.githubusercontent.com/7342321/231993893-0db22970-5a97-45c1-8cc8-2bbbe9b29a6a.png)

**Comment by ZzZombo** [comment]
I do not have any other OS unfortunately nor any antimalware program running.

**Comment by ZzZombo** [comment]
It gets stuck all the same. Do you write any logs by chance?

**Comment by bostrot** [comment]
Here is a build with extra logging. Can you try it?

https://github.com/bostrot/wsl2-distro-manager/suites/12259396937/artifacts/648996275

**Comment by ZzZombo** [comment]
Sorry, but now it gets the "Failed to parse manifest" error out of the blue. Also I can't quite figure where the logs are.

**Comment by bostrot** [comment]
My bad; here is a fixed version with logging: https://github.com/bostrot/wsl2-distro-manager/suites/12269068756/artifacts/649677106

The logs are in `%appdata%\com.bostrot\WSL Distro Manager\wslmanager_01.log`. You can also now directly upload them over the bug button in the top right of the window.

**Comment by ZzZombo** [comment]
Hello. I don't think logging works. The file only shows `WSL Manager v1.7.2 on windows "Windows 10 Pro" 10.0 (Build 19045)` and a line of the equal sign characters. The original problem remains.

**Comment by bostrot** [comment]
Could you retry with v1.7.3? It already has more logging in it than the build. Also it is more like an error log so it will only show unhandled exceptions or the specific docker image things I put in.

Another thing: could you check whether you can access the docker registry (e.g. via browser):   https://registry-1.docker.io

**Comment by ZzZombo** [comment]
If `404 page not found` in returned response any indication I think there is no issue accessing the Docker Hub. Gonna try the new version ASAP.

**Comment by ZzZombo** [comment]
OK, two things:

1. The log location was a lie, it turned out the proper log is created near the executable.
2. It contains the following:

```
 in nullPathNotFoundException: Cannot open file, path = 'G:\home\dev\WSL/distros/library_archlinux_latest.tar.gz' (OS Error: Системе не удается найти указанный путь.
, errno = 3) at #0      _File.throwIfError (dart:io/file_impl.dart:629)
#1      _File.openSync (dart:io/file_impl.dart:473)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:598)
#3      DockerImage.getRootfs (package:wsl2distromanager/api/docker_images.dart:500)
<asynchronous suspension>
#4      createInstance (package:wsl2distromanager/dialogs/create_dialog.dart:120)
<asynchronous suspension>
 in nullException: Tar file is not created at #0      DockerImage.getRootfs (package:wsl2distromanager/api/docker_images.dart:525)
<asynchronous suspension>
#1      createInstance (package:wsl2distromanager/dialogs/create_dialog.dart:120)
<asynchronous suspension>
 in null
```

I've created the folder, after creating RootFS it showed some nonsensical message and got stuck:
![image](https://user-images.githubusercontent.com/10889612/232407229-8baa680c-39b9-4d2e-a034-5868189af635.png)

I've also noticed it put temporary files in a location formed by incorrectly concatenating the specified default save location and the file path, it's missing the trailing '\' between the folder and child path, i. e. `G:\home\dev\WSLtmp<...>`. May I suggest to abolish all hand-made attempts at handling file paths and using the proper API for that, provided Dart/Flutter has such means?

**Comment by bostrot** [comment]
> OK, two things:
> 
> 1. The log location was a lie, it turned out the proper log is created near the executable.
> 2. It contains the following:
> 
> ```
>  in nullPathNotFoundException: Cannot open file, path = 'G:\home\dev\WSL/distros/library_archlinux_latest.tar.gz' (OS Error: Системе не удается найти указанный путь.
> , errno = 3) at #0      _File.throwIfError (dart:io/file_impl.dart:629)
> #1      _File.openSync (dart:io/file_impl.dart:473)
> #2      _File.writeAsBytesSync (dart:io/file_impl.dart:598)
> #3      DockerImage.getRootfs (package:wsl2distromanager/api/docker_images.dart:500)
> <asynchronous suspension>
> #4      createInstance (package:wsl2distromanager/dialogs/create_dialog.dart:120)
> <asynchronous suspension>
>  in nullException: Tar file is not created at #0      DockerImage.getRootfs (package:wsl2distromanager/api/docker_images.dart:525)
> <asynchronous suspension>
> #1      createInstance (package:wsl2distromanager/dialogs/create_dialog.dart:120)
> <asynchronous suspension>
>  in null
> ```
> 
> I've created the folder, after creating RootFS it showed some nonsensical message and got stuck:
> ![image](https://user-images.githubusercontent.com/10889612/232407229-8baa680c-39b9-4d2e-a034-5868189af635.png)
> 
> I've also noticed it put temporary files in a location formed by incorrectly concatenating the specified default save location and the file path, it's missing the trailing `\` between the folder and child path, i. e. `G:\home\dev\WSLtmp<...>`. May I suggest to abolish all hand-made attempts at handling file paths and using the proper API for that, provided Dart/Flutter has such means?

1. Weird, should be in appdata..
2. Did you declare a custom savepath?

Also you are more then welcome to open a PR for the path thing :)

**Comment by ZzZombo** [comment]
I did choose a custom save path. I'd like to accept your offer but my Dart/Flutter knowledge is minimal.

**Comment by bostrot** [comment]
Ok, it is a good point though and I will try changing the paths when I have some time today.

**Comment by bostrot** [comment]
Not sure if it already fixes your issue, but the current build should have better pathing already: https://github.com/bostrot/wsl2-distro-manager/suites/12281227851/artifacts/650535113

Can you test it?

**Comment by ZzZombo** [comment]
This hit the spot! The process finished correctly, although I've not done anything but a quick test by running the instance and issuing the `whoami` command in the shell. This does suggest the issue, if I got you correctly, lied primarily in file path handling, oh and also proper logs are not to be underestimated! Thank you for your time.

**Comment by bostrot** [comment]
Good to hear! 🎉 

Also, you are right! I totally misjudged the need for logs (and unit tests, for that matter) when starting the project, and it is a pain adding that now and will still take some time until most code is covered.

**Comment by ZzZombo** [comment]
Hey, I'm just curious if you do not mind, what exactly is the nonsensical message shown in https://user-images.githubusercontent.com/10889612/232407229-8baa680c-39b9-4d2e-a034-5868189af635.png?

**Comment by bostrot** [comment]
That is a good question. My guess is that it is the process output of trying to import a non-existing file into wsl with a malformed path:

https://github.com/bostrot/wsl2-distro-manager/blob/7682e04ed93e877e799b68165dbd5bc5f878e289/lib/dialogs/create_dialog.dart#L158

Then maybe converting it to utf8 didn't work as the method I am using for that only filters out some ascii characters. (all 0s and some non-alphabet characters; i should replace that at some point)

I am curious, when you write WSL commands in the console, what language is the response in?

**Comment by ZzZombo** [comment]
I'm not so sure? My whole OS is in Russian, `wls.exe` IIRC is in English, VMs too.

**Comment by bostrot** [comment]
It could be that WSL itself is taking the error directly from your system (with your language) and forwarding it.

Wouldn't surprise me if that is what microsoft did, tbh.

Then it gets messed up with the utf8convert function.
