### ISSUE TITLE
Creating "C:\WSL2-Distros" when Run from "D:\"

### ISSUE THREAD

**Issue by Some1OnLine** [bostrot/wsl2-distro-manager#13]
**Describe the bug**
Love the simple WSL GUI! 

I have changed/saved the "Default Distro location" from C:\WSL2-Distros" to another folder (actually a subfolder of wsl2distromanager.exe. When I launch wsl2distromanager.exe it still creates C:\WSL2-Distros folder. Is this on purpose?
The Main GUI looks to show the correct folder but whenever I create a new ubuntu instance it creates C:\WSL2-Distros\distros\....

Also any plans to add a button or something to set/enable the new bridging capabilities recently added to newer builds of WSL via .wslconfig file? 

**Desktop (please complete the following information):**
 - OS : Windows 11 Pro x64 22000.469 (21H2)
 - Version : v0.7.1
 - Source [e.g. GitHub releases, GitHub master, Windows Store]

**Comment by bostrot** [comment]
Have you checked if the version in the build folder (main branch) fixes this?

There are definitely plans for adding more WSL features. Could you add a new issue/feature request for that?

**Comment by Some1OnLine** [comment]
I just checked the release from the build folder and yes it seems to be the same with that version as well. I will add a feature request for other ideas/thoughts for future builds. Thank you!

**Comment by Some1OnLine** [comment]
Thank you. I just checked release 0.7.4 and I see the options for .wslconfig. Thanks. It does however still seem to create C:\WSL2-Distros despite launching from D:\WSLManager. Checking Default Distro Location in Settings GUI it shows D:\WSLManager\WSL2-Distros.

**Comment by bostrot** [comment]
I think I misunderstood you earlier. You were writing about it creating new instances to the wrong location + creating the default folder. I mixed those two up. 

When I create a new distro e.g.

    Name: TestDistro
    Path or distroname: Ubuntu 20.04
    Save location: [empty]
    User: [empty]

while having `D:\WSL` as the path it successfully creates the distro in `D:\WSL`.

So you are just talking about creating the C:\WSL2-Distros folder when another path is selected?

**Comment by Some1OnLine** [comment]
I was downloading "wsl2-distro-manager-main.zip" and would extract "\wsl2-distro-manager-main\build\windows\runner\Release" to D:\WSL_Manager. as soon as I run "D:\WSL_Manager\wsl2distromanager.exe" it would create a folder C:\WSL2-Distros.

However, I just downloaded v0.8.0 and tested again and it seems to be fixed in that it is not creating C:\WSL2-Distros. I will play with it some more. But at first glance it seems this bug is squashed!

I personally like to keep an app and its data in a single folder/subfolder when possible (for portability mainly).

Thank you and keep up the good work!
