### ISSUE TITLE
[FEATURE] Disk shrinking

### ISSUE THREAD

**Issue by felipecrs** [bostrot/wsl2-distro-manager#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem?

WSL2 disks only grow, and their data is never reclaimed even if the files are deleted from within WSL2.

### Solution

That's why tools like wslcompact exists: https://github.com/okibcn/wslcompact, it would be great if it could be called directly from a nice GUI like WSL2 Distro Manager.

### Alternatives

To call it from PowerShell.

**Comment by bostrot** [comment]
I just checked and all it does is basically to export the image, delete the instance and then re-import it. This can be implemented easily 👍
