### ISSUE TITLE
[BUG] DioError [bad response]: The request returned an invalid status code of 404.

### ISSUE THREAD

**Issue by bostrot** [bostrot/wsl2-distro-manager#146]
<details>
<summary>Here is the stacktrace.</summary>

<pre><code>#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:538)
#1      _RootZone.runBinary (dart:async/zone.dart:1665)
#2      _FutureListener.handleError (dart:async/future_impl.dart:162)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779)
#4      Future._propagateToListeners (dart:async/future_impl.dart:800)
#5      Future._completeError (dart:async/future_impl.dart:575)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51)
#7      _Completer.completeError (dart:async/future_impl.dart:23)
#8      Future.any.onError (dart:async/future.dart:617)
#9      _RootZone.runBinary (dart:async/zone.dart:1665)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779)
#12     Future._propagateToListeners (dart:async/future_impl.dart:800)
#13     Future._completeError (dart:async/future_impl.dart:575)
#14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:520)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
</code></pre>

</details>

The library:
 null

**Comment by Spongman** [comment]
why is this closed. this still happens.
