### ISSUE TITLE
Support for Profiles in Windows Terminal

### ISSUE THREAD

**Issue by eskaufel** [bostrot/wsl2-distro-manager#15]
**Is your feature request related to a problem? Please describe.**
When I launch Windows Terminal from the app, it always uses the default profile (color, etc.)

**Describe the solution you'd like**
If there is a profiles that match the WSL instance, use it.

**Describe alternatives you've considered**
As an alternative allow user to select profile in app.

**Additional context**
Nice app

**Comment by bostrot** [comment]
With the latest Windows Terminal version this should work now. 
Can you test it?

**Comment by eskaufel** [comment]
It works 👍
