### ISSUE TITLE
[BUG] cannot install from msix

### ISSUE THREAD

**Issue by fusionneur** [bostrot/wsl2-distro-manager#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cannot install from msix (portable zip works)

This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

### Expected Behavior

able to install

### Steps To Reproduce

dl msix wsl2-distro-manager-v1.8.4-unsigned.msix, run it

### Environment

```markdown
- Windows Version: 11
- wsl2 1.2.5.0
- fedora remix distro 38
```

**Comment by bostrot** [comment]
Yes, that is correct. That is an unsigned msix. The only thing you can do here is install the signed msix from older releases.

I'd suggest you just use a package manager (see readme) to install it.

**Comment by bostrot** [comment]
Makes sense. I updated it.
