### ISSUE TITLE
[BUG] wsl2-distro-manager opens with a blank screen 

### ISSUE THREAD

**Issue by ShmuelRonen** [bostrot/wsl2-distro-manager#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No text. After it worked just fine.
![white](https://github.com/bostrot/wsl2-distro-manager/assets/80190186/21db25f9-c01d-4e79-af7d-e73ae5a1a88b)

### Environment

```markdown
- Windows Version:Windows 10 pro
- WSL Distro Manager Version:Last
- WSL Version:
- Source:
```

**Comment by bostrot** [comment]
Can you add the exact Windows Build version? (e.g. `systeminfo ` -> `OS Version`)

Also, how did you install it? (downloaded the zip, with package manager, etc.)

**Comment by ShmuelRonen** [comment]
![os](https://github.com/bostrot/wsl2-distro-manager/assets/80190186/39b546d9-6cda-44ce-af1c-f5c34c931ba7)

**Comment by ShmuelRonen** [comment]
Yes. I install it via the zip file

**Comment by bostrot** [comment]
Ok, thanks. Am I getting it right that the blank screen will vanish after some time and you can use it normally?

**Comment by ShmuelRonen** [comment]
The blank screen has been with me for 9 hours and hasn't disappeared. Every time I open wsl2distromanager.exe

**Comment by ShmuelRonen** [comment]
ubuntu.exe works fine. but wsl2distromanager is better. I will glad if you have any solution.

**Comment by bostrot** [comment]
Is your Windows up-to-date? Could you also check whether there is a log file in `%appdata%/WSL Distro Manager/`or if that directory even exists?

**Comment by ShmuelRonen** [comment]
[wslmanager_01.log](https://github.com/bostrot/wsl2-distro-manager/files/11470313/wslmanager_01.log)

**Comment by ShmuelRonen** [comment]
![Screenshot 2023-05-13 212921](https://github.com/bostrot/wsl2-distro-manager/assets/80190186/034793f4-1759-4691-bd3a-1adabb2a7a27)

**Comment by ShmuelRonen** [comment]
The  Windows is up-to-date (10 pro)

**Comment by Peuczynski** [comment]
@bostrot This is because `shared_preferences.json` gets corrupted and becomes a binary file. @ShmuelRonen just remove the file and it will launch correctly

**Comment by ShmuelRonen** [comment]
> @bostrot This is because `shared_preferences.json` gets corrupted and becomes a binary file. @ShmuelRonen just remove the file and it will launch correctly

Thanks!!

**Comment by lzjluzijie** [comment]
Got the same issue, and I could not shutdown the app. I have to open task manager to kill it. I think this should be fixed.

**Comment by Rajeshsahoo12** [comment]
> @bostrot This is because `shared_preferences.json` gets corrupted and becomes a binary file. @ShmuelRonen just remove the file and it will launch correctly

Thanks I experienced this exact issue. And thanks for solution it worked.
