### ISSUE TITLE
[FEATURE] stop asking rating after already rated

### ISSUE THREAD

**Issue by fusionneur** [bostrot/wsl2-distro-manager#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Solution

app asking to rate on each open can be a bit annoying to dismiss it every time. possible solutions:
- stop asking when already rated (might be difficult to implement)
- ask less often
- have a toggle in the settings to disable it
- stop asking after being dismissed first time
- ???

### Anything else?

thank you for this great tool

**Comment by bostrot** [comment]
You are right, it annoys me too. Will fix that.
