### ISSUE TITLE
Error when creating a instance without specifying a Save Location

### ISSUE THREAD

**Issue by Lucino772** [bostrot/wsl2-distro-manager#18]
**Describe the bug**
When I create an instance but do not specify a **Save Location**, the instance never gets created. The status message still appears saying that the instance is being created when in reality it never really started. 

I did some debugging and found out where was the error occurring. I'm not an expert in Flutter but the errors seem to happen when getting the key `SaveLocation` from the preferences:

https://github.com/bostrot/wsl2-distro-manager/blob/0dcf2b9ddd361cb169325b6004cb6b2d575a127b/lib/dialogs/create_dialog.dart#L156-L162

**To Reproduce**
1. Go to the Home screen
2. Click on 'Add Instance'
3. Give your instance a Name
4. Select a Distro
5. *Leave the Save Location text input blank*
6. Click on 'Create'
7. In the debugging console you should see the following error (see Screenshots) 

**Expected behavior**
A default value should be supplied if the `SaveLocation` does not exists in the preferences

**Screenshots**
![image](https://user-images.githubusercontent.com/24496755/154868330-637f2f24-a57c-4229-b4db-026886cb6fe5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Build 10.0.19044
 - Version: v0.8.0
 - Source: GitHub master

**Additional context**
_Nothing to add_

**Comment by bostrot** [comment]
Should be fixed in v0.8.1.
