### ISSUE TITLE
[FEATURE] Add GUI package installer to facilitate the package installation

### ISSUE THREAD

**Issue by muhammadbahaa2001** [bostrot/wsl2-distro-manager#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem?

Not really a problem but WSL manager should have GUI package installer featur and should support DEB, RPM and etc...

### Solution

Add GUI package installer to facilitate the package installation.

### Anything else?

Different types of package formats such as: DEB, RPM, PKG.TAR.XZ and etc...

**Comment by bostrot** [comment]
Can you explain what you mean with GUI installer?

e.g. selecting a .deb from the GUI that starts the installation (command) in a distro?

**Comment by muhammadbahaa2001** [comment]
> Can you explain what you mean with GUI installer?
> 
> e.g. selecting a .deb from the GUI that starts the installation (command) in a distro?

I mean as you would sideload APK to WSA using WSATools.
So, yes.

**Comment by bostrot** [comment]
I am closing this as it's not planned for now. I don't see why there needs to be a GUI option for that. Convince me otherwise if you think I am mistaken :)

**Comment by muhammadbahaa2001** [comment]
> I am closing this as it's not planned for now. I don't see why there needs to be a GUI option for that. Convince me otherwise if you think I am mistaken :)

No, it's ok. Just it was a suggestion, because installing Linux packages wether from repository or from sideloading cause a headache slightly.
