### ISSUE TITLE
[BUG] wsl.conf not created after configuration changes

### ISSUE THREAD

**Issue by tempwswm** [bostrot/wsl2-distro-manager#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to change the host for instance using this software, but it did not work, I checked that the wsl file was not created, I created it manually and it was not modified.

### Expected Behavior

The file needs to be created and contain key-value pairs.

### Steps To Reproduce

1. create an instance using dockerhub:debian:bullseye
2. passwd root manually
3. install nano sudo git
4. stop instance
5. change hostname setting using this software
6. not work
7. echo -e "[network]\nhostname=guitest" >> /etc/wsl.conf 
8. it works
9. change hostname setting using this software again
10. not work

### Environment

```markdown
- Windows Version: "Windows 10 Pro" 10.0 (Build 19045)
- WSL Distro Manager Version:WSL Manager v1.8.4 on windows
- WSL Version:2
- Source: GitHub releases
```

### Anything else?

[maybe error here](https://github.com/bostrot/wsl2-distro-manager/blob/5d57811213aef14182a73173ec45f0db31c01b92/lib/dialogs/create_dialog.dart#LL181C1-L181C1) 
I tried these lines of commands, this line will waitting user(me) to input password twice. Please check.
[this issue](https://github.com/bostrot/wsl2-distro-manager/issues/159) may also need to be handled together.

Poor English, thanks

**Comment by bostrot** [comment]
The lines you provided are only when you create a user for non-docker images.

I tried reproducing your steps, but it works for me:

```bash
cat /etc/wsl.conf
[network]
hostname = testhost
```
