### ISSUE TITLE
[BUG] Unknown error when creating an Ubuntu 22.04 WSL VM

### ISSUE THREAD

**Issue by f0xcb** [bostrot/wsl2-distro-manager#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a new VM with Ubuntu 22.04 selected as the distribution, an unknown error occurs.

### Expected Behavior

When creating an Ubuntu 22.04 VM, a WSL VM should be created successfully

### Steps To Reproduce

1. Add an instance
2. Fill name and choose a distro
3. Click on "create"

### Environment

```markdown
- Windows Version: Windows 11 Pro Version 22H2 (Build: 22621.1848)
- WSL Distro Manager Version: v1.8.5 
- WSL Version: 2
- Source: Windows Store
```

### Anything else?

Screenshot of the error:
![2023-06-25 18_03_18-WSL Manager](https://github.com/bostrot/wsl2-distro-manager/assets/60115108/9910995c-02c1-43db-9c69-373f254fd00a)

**Comment by f0xcb** [comment]
I could not find any error logs, if you can say me where i find the app specific error logs i can post them here.

**Comment by bostrot** [comment]
Should be in "%appdata%/Bostrot/WSL Distro Manager"

**Comment by bostrot** [comment]
Ok, sorry, my bad: `C:\Users\erict\AppData\Roaming\com.bostrot\WSL Distro Manager\wslmanager_01.log`
In my case.

**Comment by taifuranowar** [comment]
[wslmanager_01.log](https://github.com/bostrot/wsl2-distro-manager/files/11910164/wslmanager_01.log)

**Comment by f0xcb** [comment]
It's so strange... I can't find anything under your mentioned path and also when I use the explorer search I only come out in a temporary folder which contains an empty log file.

**Comment by bostrot** [comment]
At least from the log @taifuranowar uploaded it seems this is a permission error. So changing the paths might already fix that. Closing this for now as I have heard nothing back though. Please create a new ticket or re-open otherwise.
