### ISSUE TITLE
[BUG] 0x803f8001 after installing via winget

### ISSUE THREAD

**Issue by hakimdotdev** [bostrot/wsl2-distro-manager#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to run after installing  the wsl2manager via winget will initially result in a 0x803f8001 error.

### Expected Behavior

Being able to run it

### Steps To Reproduce

```winget install Bostrot.WSLManager```

### Environment

```markdown
- Windows Version: Windows 11 22H2 (10.0.22621.1848)
- WSL Distro Manager Version: Current Winget Package
- WSL Version: WSL2 1.2.5.0
- Source: Winget
```

**Comment by bostrot** [comment]
The winget version is outdated (see README)
