### ISSUE TITLE
[BUG] Translation of `snippet`

### ISSUE THREAD

**Issue by wohenbushuang** [bostrot/wsl2-distro-manager#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently, the `quick action` is changed to `snippet`, and `片段` in Chinese. I'm not sure `snippet` actually have a meaning related to code in the dictionary, but it seems really weird in Chinese.

### Expected Behavior

I hope that the translation can be `code snippet` in English, and `代码片段` in Chinese. It will help people (such as me) better understand when they use this app the first time

### Environment

```markdown
- WSL Version:v1.8.5
```

### Anything else?

Thanks again for your effort on this useful GUI application.

**Comment by bostrot** [comment]
This should fix it: https://github.com/bostrot/wsl2-distro-manager/pull/204/files
