### ISSUE TITLE
[BUG] Carsh when trying to change default distro location

### ISSUE THREAD

**Issue by wohenbushuang** [bostrot/wsl2-distro-manager#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Carsh when trying to change default distro location

### Steps To Reproduce

See gif below

### Environment

```markdown
- Windows Version: Win 10
- WSL Distro Manager Version: v1.8.5
- WSL Version: 2
- Source:
```

### Anything else?

![crash](https://github.com/bostrot/wsl2-distro-manager/assets/15613184/e1c10457-e14f-420b-b2a8-307fbf663c6d)

**Comment by 36k** [comment]
The bug caused by file_picker, changing the version to 5.3.1 can solve this problem

**Comment by bostrot** [comment]
@36k Will update that with the next release. Thanks!

**Comment by wohenbushuang** [comment]
@bostrot I've upgraded to v1.8.9, and this bug still exists.
