### ISSUE TITLE
[BUG] *gc[v error when creating an Ubuntu 22.04 WSL VM

### ISSUE THREAD

**Issue by KnightBlood** [bostrot/wsl2-distro-manager#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

*gc[v error when creating an Ubuntu 22.04 WSL VM

### Expected Behavior

When creating an Ubuntu 22.04 VM, a WSL VM should be created successfully

### Steps To Reproduce

1.Add an instance
2.Fill name and choose a distro
3.Choose save location (Refs)
4.Click on "create"

### Environment

```markdown
- Windows Version: 
- WSL Distro Manager Version:  v1.8.5 
- WSL Version: 2
- Source: github 
```

### Anything else?

![image](https://github.com/bostrot/wsl2-distro-manager/assets/14256591/40c9318b-360e-4b3c-bdd9-03f0a14137ee)
![image](https://github.com/bostrot/wsl2-distro-manager/assets/14256591/26e3e9af-7c78-41db-a262-a0ff82f3a277)
![image](https://github.com/bostrot/wsl2-distro-manager/assets/14256591/f3e78db3-92e0-4f64-995e-1d78b69befc0)

**Comment by bostrot** [comment]
Does v1.8.6 fix it?

**Comment by Paper-Dragon** [comment]
v1.8.14 also have this problem

![图片](https://github.com/user-attachments/assets/34ac261a-711d-49db-ab59-bec523dac1fe)

**Comment by Paper-Dragon** [comment]
@bostrot

**Comment by bostrot** [comment]
> @bostrot 

Please create a new issue. Thanks!

**Comment by KnightBlood** [comment]
> > @bostrot
> 
> Please create a new issue. Thanks!

这个问题的原因是没有启用hyper-v和wsl 
启用后就不会报错了 
我当时是发现自己没有启用这俩

**Comment by Paper-Dragon** [comment]
经过检查 Hyper-v 和 wsl2已经开启， 创建的时候docker wsl正在运行，我这个问题和你的不一样

**Comment by cacard** [comment]
same error, can't fix !!!
