### ISSUE TITLE
[BUG] the terminal window not responsive

### ISSUE THREAD

**Issue by unapregunta** [bostrot/wsl2-distro-manager#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I click on the ubuntu button - the terminal window opens - but it is not responsive.
The shell prompt does not show. You can't close the window.

I don't have time to test everything else.

### Expected Behavior

A terminal window should work like terminal windows do.

### Environment

```markdown
- Windows Version:
- WSL Distro Manager Version:
- WSL Version:
- Source:
```

### Anything else?

Give me my money back.

**Comment by bostrot** [comment]
What version of Windows are you using?

**Comment by bostrot** [comment]
Closing as there was no feedback.
Feel free to create a new ticket or re-open this one once you have provided more info about it.
