### ISSUE TITLE
[BUG] <crashed unexpectedly while spectify an folder>

### ISSUE THREAD

**Issue by qinyihust** [bostrot/wsl2-distro-manager#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

specify a folder for default distro location，
![image](https://github.com/bostrot/wsl2-distro-manager/assets/27180291/e8a0a78f-193c-496f-8883-961f674a9320)
process will crashed unexpectedly in 2 seconds, every time.

### Expected Behavior

process work normally

### Steps To Reproduce

1. run WSL Distro Manager
2. click settings button
3. click "Default Distro Location"
4. click folder button, select  any specified folder
5. process window disappear in 2 seconds.

### Environment

```markdown
- Windows Version: windows 11  family, 22H2, 22621.2283, zh-cn
- WSL Distro Manager Version: v1.8.9
- WSL Version: v1.2.5.0
- Source: GitHub releases
```

### Anything else?

none

**Comment by LordHumphrey** [comment]
Maybe not support Non-C drive？

**Comment by si618** [comment]
Also crashes for me on a logical drive that is also on my C drive, but works on a separate drive that is the primary partition. So I suspect it's not happy with logical drives in extended partitions. However, it only appears to be the folder selection dialog that crashes i.e. it works fine if I create a folder in a logical drive externally from the app and then type in the path.

Couldn't find any logs other than windows event log which showed `Exception code: 0xc0000005`

**Comment by Spongman** [comment]
crashes for me too when picking a directory on my c drive.

**Comment by wohenbushuang** [comment]
may be duplicated with my issue #197

**Comment by HadiJadallah** [comment]
Same here.
1- Crashes after selecting a new folder yet the selected folder is saved / updated in "shared_preferences.json"??

2- In shared_preferences.json, "flutter.SaveLocation":"D:\\wsl2_vhdx" but "C:\WSL2-Distro" is displayed which is confusing.

**Comment by dan788** [comment]
quick work around :
If you just type the new folder location in the selection area then click save it works

**Comment by Spongman** [comment]
I don't know how's that's supposed to fix the issue.

the bug is, and remains, here: https://github.com/bostrot/wsl2-distro-manager/blob/46a356270c4ebf15ea44665039ff289a0375c994/lib/components/constants.dart#L7

it's a bug for an application to be _reading_, _writing_, or _creating_ _anything_ in the `c:\` directory.

**Comment by bostrot** [comment]
I can't reproduce this after this PR. Usually C: is writable if not defined otherwise by company or personal permissions.

**Comment by Spongman** [comment]
No this is false c: is only writable if you disable UAC. The Windows logo program has limited applications to only writing to allowed specified directories. Honestly I’m surprise this behavior made it past the MS store acceptance. Writing to C: is a bug.
