### ISSUE TITLE
[BUG] unspecified error docker image

### ISSUE THREAD

**Issue by runalsh** [bostrot/wsl2-distro-manager#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

trying to add image from dockerhub, for example dockerhub:gitlab/gitlab-ce.
error after sucessfull downloading layers. wslmanager_01.log is clean, nothing about error
![dd](https://github.com/bostrot/wsl2-distro-manager/assets/21105673/914dfb2d-02ad-4ece-bb46-8609cf740c66)

### Expected Behavior

process work normally

### Steps To Reproduce

1. run WSL Distro Manager
2. create a new instance
3. image dockerhub:gitlab/gitlab-ce
4. sucessfull downloading layers
5. file present /distros/gitlab_gitlab_ce_latest.tar.gz
6. show error on screen

### Environment

```markdown
- Windows Version:Windows 10 Pro 10.0.19045
- WSL Distro Manager Version:1.8.10.0
- WSL Version:2.0.4.0
- Source:GitHub releases
```

### Anything else?

none

**Comment by bostrot** [comment]
V1.8.15 should fix it. Can you test it?

I will close this for now. If it does not fix it feel free to create a new ticket or re-open this one.

**Comment by runalsh** [comment]
Working fine, thanks!
