### ISSUE TITLE
[BUG] The app interface is not loading

### ISSUE THREAD

**Issue by kintolayli** [bostrot/wsl2-distro-manager#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I only see the program with a white empty interface
![2023-11-16 162448](https://github.com/bostrot/wsl2-distro-manager/assets/43316003/b0a47a4d-204f-46d6-bdd2-f5a5fe39e97b)

### Expected Behavior

I expect to see the standard interface of the program

### Steps To Reproduce

Probably the problem is only on my desktop computer, since the application works on a laptop

### Environment

```markdown
- Windows Version: Windows 11 Pro 22H2
- WSL Distro Manager Version: v1.8.11
- WSL Version: 2
- Source: GitHub releases, GitHub master
```

### Anything else?

Great app! However, I managed to use it on my desktop for one day.  The next day it stopped working. When I launch wsl2distromanager.exe , instead of the interface, just a white window is loaded.  Of course, I have tried various ways to make it work - rebooting windows, installing previous versions of the application - unsuccessfully. I also compiled the application from the source code, but this did not lead to success. This application is also installed on my laptop, and it works fine there.

**Comment by sbosk** [comment]
I have encountered the same bug as well.

**Comment by HamedJafarzadeh** [comment]
same bug for me as well.

**Comment by si618** [comment]
Same here. Also on v1.8.11, Win11 23H2.

**Comment by kintolayli** [comment]
> a quick debug showed that there is apparently problem with user data, cleaning the following directory fixed the problem for me :
> 
> `<USERFolder>\AppData\Roaming\com.bostrot`

Thank you, this is worked for me
