### ISSUE TITLE
[BUG] Winget install doesn't work

### ISSUE THREAD

**Issue by JStein01** [bostrot/wsl2-distro-manager#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I try to install and run the program I just get this error:
![image](https://github.com/bostrot/wsl2-distro-manager/assets/51428654/fd24a255-21be-4866-b894-981912db26df)

### Expected Behavior

The program opens and runs with no error.

### Steps To Reproduce

1.`winget install Bostrot.WSLManager`
2. Run "WSL Manager" from Start Menu
3. ![image](https://github.com/bostrot/wsl2-distro-manager/assets/51428654/fd24a255-21be-4866-b894-981912db26df)

### Environment

```markdown
- Windows Version: Windows 11 Pro Version 22H2 Build 22621.2715
- WSL Distro Manager Version: v1.8.11
- WSL Version: 2.0.9.0
- Source: Windows Package Manager
```

**Comment by JStein01** [comment]
P.S. I am in fact signed in to the MS Store just forgot to put that b4

**Comment by zuilintan** [comment]
I am using scoop, it works for me

**Comment by bostrot** [comment]
Closing this as the README already says "The winget package is outdated" and its not a prio.
