### ISSUE TITLE
reader writer

### ISSUE THREAD

**Issue by ACewoods7** [bostrot/wsl2-distro-manager#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 Pro Insider Preview Build 22471]
 - Version [e.g. v0.4.0]
 - Source [e.g. GitHub releases, GitHub master, Windows Store]

**Additional context**

**Comment by ACewoods7** [comment]
install reader writer

**Comment by bostrot** [comment]
Hi,

1. please use the template and fill in the fields.
2. I am not sure what you mean with 'install reader writer'. Please elaborate. Thanks.

**Comment by bostrot** [comment]
Edit the text before reopening this issue.
