### ISSUE TITLE
[BUG] "Create a new instance" window does not close after successfully creating the new instance

### ISSUE THREAD

**Issue by silasalves** [bostrot/wsl2-distro-manager#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After going through all the steps to create a new instance, the window is not closed, thus allowing a careless user to assume something went wrong and clicking on `Create` again

![image](https://github.com/bostrot/wsl2-distro-manager/assets/4983290/5330d424-32a8-4d44-95e3-07a48f4f347f)

### Expected Behavior

I think the window should be closed. There might be a use case for creating multiple instances, in which the current behaviour would save some time (i.e. the user wouldn't have to click in "Create new instance" to open that window several times). However, this use case seems more like an "exception" for most users.

### Steps To Reproduce

This is what I did:

1. Unzip `wsl2-distro-manager-v1.8.14.zip`
2. Run `wsl2distromanager.exe` for the first time
3. Click on `Add an Instance`
4. Set name
5. Select `Ubuntu 22.04`
6. Set a path in a different drive (e.g. D:\)
7. Set user as "user"
8. Click on `Create`

### Environment

```markdown
- Windows Version: Windows 11 Home 23H2
- WSL Distro Manager Version: 1.8.14
- WSL version: 2.1.5.0
- Kernel version: 5.15.146.1-2
- WSLg version: 1.0.60
- MSRDC version: 1.2.5105
- Direct3D version: 1.611.1-81528511
- DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
- Windows version: 10.0.22631.3672
- Source: GitHub releaes
```

### Anything else?

Thanks for the amazing software! =D

This is a small issue, so I would leave it with a low priority.

**Comment by bostrot** [comment]
This is actually wanted behavior.

**Comment by silasalves** [comment]
If this is the wanted behaviour, then I guess the issue is clarified and closed. Thanks! =)
