### ISSUE TITLE
[BUG] Exception when WT (Terminal) not installed

### ISSUE THREAD

**Issue by RedyAu** [bostrot/wsl2-distro-manager#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click "Open with Windows Terminal", an error message appears (as I don't have Terminal installed):

`Windows cannot find 'wt'. Make sure you've typed the name correctly, then try again.`

### Expected Behavior

Definitely make a more useful error message than this: "Windows Terminal is not installed, please install it for this feature to work".

Or you could even prompt the user to download Windows Terminal.

But the best would be to **fall back to `cmd`**. I, for one, don't like the bloat and slowness of WT, and would prefer plain cmd, or even PowerShell.

### Steps To Reproduce

1. Have no WT installed
2. Click `Open with Windows Terminal`

### Anything else?

Thank you for this great software, it feels like it should be part of Windows <3

**Comment by RedyAu** [comment]
@bostrot I just realized, that this is Flutter :P Might be able to submit a quick patch!

**Comment by bostrot** [comment]
I will close this for now as your PR is merged. If there is still something wrong or not as expected feel free to open a new issue.
