### ISSUE TITLE
[BUG] Installing with WSL2.0

### ISSUE THREAD

**Issue by recdown** [bostrot/wsl2-distro-manager#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing the system in WSL 2.0, it fails to start due to a violation. Switching back to version 1 allows it to start.

### Environment

```markdown
- Windows Version:
- WSL Distro Manager Version:
- WSL Version:
- Source:
```

**Comment by bostrot** [comment]
Can you provide more info about this?
- Windows Version:
- WSL Distro Manager Version:
- WSL Version:
- Source:

would be a good start. Closing until then. Please re-open once you have filled it.
