### ISSUE TITLE
[BUG] *gc[v error when creating an Apline 3.19.0

### ISSUE THREAD

**Issue by Paper-Dragon** [bostrot/wsl2-distro-manager#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

*gc[v error when creating an Apline 3.19

### Expected Behavior

maybe can not use wsl command? IDK

### Steps To Reproduce

1.Add an instance
2.Fill name and choose a distro
3.Choose save location
4.Click on "create"

### Environment

```markdown
- Windows Version: windows "Windows 10 Enterprise" 10.0 (Build 26100)
- WSL Distro Manager Version: WSL Manager v1.8.14
- WSL Version: 2 
- Source:Github
```

### Anything else?

![377367351-34ac261a-711d-49db-ab59-bec523dac1fe](https://github.com/user-attachments/assets/18b093b9-bc65-4415-aee9-d44d678cb1bd)

**Comment by goparrohmat** [comment]
try cmd/powershell  execute 
```
wsl --update
```

**Comment by bostrot** [comment]
Does [1.8.15](https://github.com/bostrot/wsl2-distro-manager/releases/tag/v1.8.15) fix it?

**Comment by bostrot** [comment]
Closing for now. If 1.8.15 does not fix it please re-open this.
