### ISSUE TITLE
Screen size

### ISSUE THREAD

**Issue by josemtella** [bostrot/wsl2-distro-manager#4]
My laptop has a screen resolution of 3480x2160 . . . and therefore there is a scale factor in display of 250%. WSL2 manager does not preserve the screen size with which it is resized, so starting up always comes out with a tiny screen that needs to be enlarged. This does not happen in other apps.

**Comment by josemtella** [comment]
![image](https://user-images.githubusercontent.com/24353442/140089077-a795855f-8b5a-4584-9d14-b24ab98792e5.png)

**Comment by josemtella** [comment]
![image](https://user-images.githubusercontent.com/24353442/140089544-c229b997-6018-46b8-b689-1df07271606d.png)

**Comment by bostrot** [comment]
Commit 631aa2c88a77bc8c99644a7cf1ccf7eb5dd4ab52 should fix this.
This is in release [v0.5.2](https://github.com/bostrot/wsl2-distro-manager/releases/tag/v0.5.2).

**Comment by josemtella** [comment]
Yes...working.  But...

![image](https://user-images.githubusercontent.com/24353442/140165930-2eb0ff9d-2b78-4610-9a43-f5ff25922204.png)

and download the same version

**Comment by bostrot** [comment]
The latest release with commit 79e0053eb5b01a1af4345baa2184d198c1e177f6 should fix that.
