### ISSUE TITLE
Default distro location is not used by copy command

### ISSUE THREAD

**Issue by denskh** [bostrot/wsl2-distro-manager#40]
**Describe the bug**
Default distro location is configured to D:\WSL however copy command saves files into C:\WSL2-Distros. 

**To Reproduce**
1. Configure default location in settings.
2. Import WSL2 distro.
3. Click Copy to create distro copy

**Expected behavior**
Expect copy to be created under location configured as default.

**Screenshots**
![image](https://user-images.githubusercontent.com/16804863/169537486-ae47da49-0f97-411d-a4e2-9ddc5f057d99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WSL Manager v1.1.0

**Comment by bostrot** [comment]
This is fixed in v1.3.0

**Comment by denskh** [comment]
Thanks for a quick turn around! 1.3.0 uses default setting, but seems like it uses parent folder, for example if my configuration is D:\WSL\Bak it would copy images to D:\WSL. It is now works for me, but would be nice for it to use exact folder lcoation:

![image](https://user-images.githubusercontent.com/16804863/169664144-745c7da9-8337-4934-a7f9-d7dca1e04c51.png)

**Comment by bostrot** [comment]
Thanks for the report. Should be fixed in v1.3.1 that also fixes some other directory issues.
