### ISSUE TITLE
Version 1.3.1 is not signed by a trusted certification.

### ISSUE THREAD

**Issue by hurrycaner** [bostrot/wsl2-distro-manager#42]
**Describe the bug**
Unable to install version 1.3.1 using signed installer.

**To Reproduce**
1. Download [wsl2-distro-manager-v1.3.1-signed-installer.msix](https://github.com/bostrot/wsl2-distro-manager/releases/download/v1.3.1/wsl2-distro-manager-v1.3.1-signed-installer.msix)
2. Run
3. See error

**Expected behavior**
Able to install it.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 21H2 fully updated (19044.1706)
 - Version 1.3.1

**Comment by bostrot** [comment]
I guess we have to wait until Microsoft approves the certificate. I was hoping that wasn't needed as the install worked on my local machine. Till then you should use the.zip to start the application.

**Comment by hurrycaner** [comment]
Would be nice to mention this at the project readme :)

**Comment by bostrot** [comment]
Yes, you are right. I uploaded the misx for the first time in the release 1.3.0 so it is pretty new :)

Also it seems each version/build has to be signed + approved by Microsoft for the certificate to be working. 

I will update this issue once they are done with it so lets see if that works.

**Comment by bostrot** [comment]
Update: they processed it so please try again.

**Comment by hurrycaner** [comment]
Still same error

**Comment by bostrot** [comment]
So I have read up on this and I mixed up how the certification process works. Microsoft signs the package again with their own certificate, after uploading. Even though it is already signed. 
 
So I only see the way that users would have to install the certificate first or allow untrusted sources for apps.

**Comment by bostrot** [comment]
I just added the certificate to the [release assets](https://github.com/bostrot/wsl2-distro-manager/releases/tag/v1.3.1) (`wsl2-distro-manager-v1.3.1-public-certificate.cer`) so you could probably install the app once you added that certificate.
