### ISSUE TITLE
Error downloading any distro

### ISSUE THREAD

**Issue by averyhox** [bostrot/wsl2-distro-manager#44]
**Describe the bug**
When creating a new instance with any distro / Turnkey, the application starts "creating the instance", then quickly changes to "Error downloading: [any distro].

**To Reproduce**
1. Go to Add an Instance
2. Select any available distro
3. Click Create
4. See error at bottom of application

**Expected behavior**
The application should download the distro or turnkey

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2, Build 22000.708
 - Version 10.0.22000
 - Source: Windows Store

**Additional context**
- Ran application as regular user
- Ran application as admin user
- Changed "Extra repo for Distros" to known good repo
- Changed download location from C:\WSL2-Distro to C:\Users\[Name]\WSL2-Distro

**Comment by bostrot** [comment]
Thanks for the report!

What version are you using? 1.3.2?

Unfortunately I can only reproduce some Turnkey containers not downloading but the "default" ones work for me (I tested Ubuntu 22.04, Ubuntu 16.04). 

Can you check the C:\WSL2-Distro\distros folder if there are any downloaded images? (also check their size. If they are only <1MB there went something wrong with the download) If there are any downloaded distros try to delete them and try creating a distro again.

Could you check if the C:\WSL2-Distro folder is writable? (no antivirus or windows ransomware application blocking it)
Might be a weird question to ask but do you have by any chance a slow internet connection? It could be that the download chunks are too big.

Also another thing you can try: Try using version 1.3.1 if you are using 1.3.2 and check if the older version works.

**Comment by averyhox** [comment]
I was using version 1.3.2 to get the download error.

I tried using Version 1.3.1 and it works great.  Same folder and options --- the download and install started immediately.

**For additional information on 1.3.2:**
- The C:\WSL2-Distro folder would populate with the request distro folder, so it seems there were not write permission issues or the folders wouldn't be created
- The C:\WSL2-Distro folders created for each distro were empty
- I use Windows Defender and have no notifications within my history for permission issues
- I use Unifi for firewall and it blocked no communication during that time.

**Comment by bostrot** [comment]
I see, so it has to be something with the buffering I worked on in 1.3.2.
Have you tried deleting the C:\WSL2-Distro\distros folder to see if that changes anything?

Also I have created an extra build for you with a lower chunk size. I don't really think that this is the issue here but it would be nice if you could try it anyways. With this build there should be at least either a `1` or a `2` in front of the error message. Could you tell me which one it is?

[wsldistromanager_test_build.zip](https://github.com/bostrot/wsl2-distro-manager/files/8886657/wsldistromanager_test_build.zip)

**Comment by averyhox** [comment]
Your test build works, but was extremely slow compared to 1.3.1.  It also locked up my computer when I cancelled the download.  1.3.1 was extremely quick.

Not sure if those details help or not.

**Comment by bostrot** [comment]
Thank you, they are helping a lot!

I guess this really is about the buffer size then. I set it on 16KB with the test build. This also explains why the download is so slow.

Did you cancel the download by pressing on the 'X' or just exiting the program?

**Comment by averyhox** [comment]
I pressed the X.

v1.3.3_test_build failed to download with the error below
"2: Error downloading: Debian Turnkey Wordpress 16.1"

Using this exact wordpress image as it worked with 1.3.1.

**Comment by bostrot** [comment]
Version 1.3.3 under [releases](https://github.com/bostrot/wsl2-distro-manager/releases) should fix this by reverting to the old downloading function. Could you report on how fast the download speed is compared to downloading it directly via the browser? The download links can be found in the [images.json](https://github.com/bostrot/wsl2-distro-manager/blob/main/images.json) file.
