### ISSUE TITLE
Error in 'Open with File Explorer'

### ISSUE THREAD

**Issue by tushev** [bostrot/wsl2-distro-manager#46]
**To Reproduce**
1. Click on  'Open with File Explorer' on any distro
2. The app attempts to open `\\wsl.localhost\{DISTRO_NAME}`
3. See error

**Expected behavior**
The correct path (well, at least on my machine) is `\\wsl$\{DISTRO_NAME}`

**Screenshots**
![image](https://user-images.githubusercontent.com/18406797/182097729-851a6a4e-bc0e-4cfd-b9a1-3be2fe887bff.png)
The correct path :
![image](https://user-images.githubusercontent.com/18406797/182098556-516618cb-dd97-424c-8789-ad3e91636ceb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Version: 1.3.3
 - Source: Windows Store

**Comment by bostrot** [comment]
This looks like a version issue as described here: https://github.com/bostrot/wsl2-distro-manager/issues/23

Try updating Windows and WSL. Also check that you are using WSL2. ([Here](https://docs.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2 ) is a guide on how to upgrade WSL1 to WSL2.

**Comment by tushev** [comment]
Yes, I can confirm that I have WSL 2. I'm also on the latest version of Windows for my branch (Education/Enterprise).

**Comment by bostrot** [comment]
You said you are using 21H1. 21H2 should be the latest on the enterprise channel. Could you recheck that?

Also on the latest Windows 11 and the 10 builds I tested the current path works just fine:
![image](https://user-images.githubusercontent.com/7342321/182411833-fbb3f8d8-8e73-4047-8690-97adb4e520e7.png)

**Comment by tushev** [comment]
I've checked on another machine running 21H2, the problem still persists there, and I get the same error. I've also [found the release note](https://blogs.windows.com/windows-insider/2021/04/07/announcing-windows-10-insider-preview-build-21354/#:~:text=The%20default%20path%20to%20access%20Linux%20files%20from%20Windows%20using%20the%20Windows%20Subsystem%20for%20Linux%20has%20been%20changed%20from%20%60%5C%5Cwsl%5C%5C%60%20to%20%60%5C%5Cwsl.localhost%5C%5C%60%20to%20improve%20performance%20and%20reliability.%20You%20will%20still%20be%20able%20to%20access%20Linux%20files%20using%20%60%5C%5Cwsl%24%5C%5C%60.) about the change from `\\wsl$` to `\\wsl.localhost\`. However, this does not solve my problem.

I've also run the commands suggested here: https://superuser.com/a/1726340
``` bash
user@name:~$ p='\\wsl$\Ubuntu-20.04\home'
user@name:~$ wslpath -w $(wslpath -u $p)
\\wsl$\Ubuntu-20.04\home
```
and I'm getting `\\wsl$`, not `\\wsl.localhost\` 🤷‍♂️.

Ideally, I would love to have an option for choosing between `\\wsl$` and `\\wsl.localhost\` if auto-detection doesn't work (could be not even in UI, but somewhere in config). Thanks!

**Comment by bostrot** [comment]
I see. I guess that changes somewhere after/around 21H2 then. I just checked with a Windows 11 21H2 build 22000 and that is already changed to `wsl.localhost` there. 

The windows build numbers are kind of confusing with older releases having higher numbers :/

According to the article it changed with build 21354 then. Can you tell me if you are using a build prior to that?
Also, could you check if the open vscode button works with your build?

**Comment by bostrot** [comment]
I quickly put together a build. Can you test if it works for you?

[wsl2distromanager-v1.3.4.zip](https://github.com/bostrot/wsl2-distro-manager/files/9244984/wsl2distromanager-v1.3.4.zip)

**Comment by tushev** [comment]
Yes, it works correctly! Thanks a lot!

P.S. I tested on OS build is `19044.1826`.

VS Code button starts downloading its packages (both in 1.3.3 & 1.3.4). I don't want it, so I terminate it with CTRL+C before download completes.
