### ISSUE TITLE
v1.4.0: Does not start plugin DLLs missing?

### ISSUE THREAD

**Issue by valsamis-d** [bostrot/wsl2-distro-manager#49]
**Describe the bug**
The latest version does dot start. 3 error messages state that the following are missing:

```
screen_retriever_plugin.dll
flutter_acrylic_plugin.dll
window_manager_plugin.dll

```

**To Reproduce**
1. Copy contents of _wsl2-distro-manager-v1.4.0.zip"_to a folder
2. Double-click on _wsl2distromanager.exe_
3. Error messages state that the DDLs are missing

**Expected behavior**
Open WSL2 Distro Manager

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2 Build 19044.1826

**Comment by bostrot** [comment]
Thanks for the report! I forgot to include those in the CI job. I just updated the release under 1.4.0, please try it.

**Comment by valsamis-d** [comment]
> Thanks for the report! I forgot to include those in the CI job. I just updated the release under 1.4.0, please try it.
> 
> EDIT: Added into build job with [06968af](https://github.com/bostrot/wsl2-distro-manager/commit/06968afe6a8d6fbde22fb0c1b7ead584f2e17936)

Solved! Thanks for the quick fix @bostrot :)
