### ISSUE TITLE
installation via cmdlet winget

### ISSUE THREAD

**Issue by brenocrs** [bostrot/wsl2-distro-manager#5]
push the releases from this app in the [winget database](https://github.com/microsoft/winget-pkgs), so it can be easily avaliable for other dev's. 
[winget ](https://github.com/microsoft/winget-cli)is the official microsoft cmdlet for app installation through command line, a lot of dev is using to automate the instalation and setup of a windows environment, and appers that any app can be avaliable since the main source of packages is maintained by community

**Comment by bostrot** [comment]
Just submitted a PR (https://github.com/microsoft/winget-pkgs/pull/34915) with commit ddc8555e44e7bf6fdcb182e6796c001ec2383c4a.
