### ISSUE TITLE
Incorrect positioning of tooltips for distro icons causes the tooltips to pop in then instantly disappear when mousing over the icons

### ISSUE THREAD

**Issue by AtomicHaggis** [bostrot/wsl2-distro-manager#51]
**Describe the bug**
The **Open with File Explorer**, **Open with VS Code** and **Settings** icon tooltips in each distro's section is wrongly positioned and pops in then disappears when I mouse over the folder icon.  The tooltips for the Copy, Rename and Delete icons are all positioned correctly.

**To Reproduce**
See the attached screencap.

**Expected behavior**
The tooltips should all be positioned to the right of the mouse cursor

**Screenshots**
https://user-images.githubusercontent.com/97291028/189522855-36d9f0c1-11ae-430d-8df8-7254aa275711.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Insider Beta Build 22621
 - Version:  v1.4.0
 - Source:  GitHub releases

**Comment by bostrot** [comment]
Should be resolved with 1.4.1. Can you check that?
