### ISSUE TITLE
Add a new distribution

### ISSUE THREAD

**Issue by kuya-carlo** [bostrot/wsl2-distro-manager#52]
**Distribution name**
Fedora

**Distribution versions**
33, 36

**Link to wsl rootfs (leave empty if unknown)**
https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-GCP-36-1.5.x86_64.tar.gz

**Additional context**
This is a great project. So does Fedora. I think adding fedora is a great thing as I want a stablest, nicest distro in wsl.

**Comment by bostrot** [comment]
Either the link you sent has a typo or the local mirror is down. Can you check if the link is working for you?
