### ISSUE TITLE
Latest Ubuntu 22.04 release contains no wsl-rootfs

### ISSUE THREAD

**Issue by hedwiggggg** [bostrot/wsl2-distro-manager#58]
https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64-wsl.rootfs.tar.gz doen't exist. 

https://cloud-images.ubuntu.com/releases/22.04/release-20220923/ is the latest release with the `ubuntu-22.04-server-cloudimg-amd64-wsl.rootfs.tar.gz`.

This is not really a bug and I don't know what to do about it either, because being locked to a particular version a) involves maintenance and b) you obviously won't always get the latest version

**Comment by bostrot** [comment]
Thanks for reporting. I updated it to the 20220923 release for now. 
It looks like it is now contained in the archive [ubuntu-22.04-server-cloudimg-amd64-root.tar.xz](https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64-root.tar.xz). For making a tar.xz work there has to be some extracting done before that though.

**Comment by bostrot** [comment]
Closing for now as Ubuntu apparently decided not to put wsl rootfs' in their 22.04 & 22.10 releases anymore. We'll just stick with an older build for now. 

For the future, issue #86 describes the problem better.

**Comment by hedwiggggg** [comment]
Just curious, does the `*-root.tar.xz` work with wsl? I think wsl only needs the rootfs. I've successfully exported a rootfs from a docker-image before and imported it into wsl (see https://source.coveo.com/2019/10/18/wsl-from-dockerfile/).

**Comment by hedwiggggg** [comment]
```
PS C:\Users\***\Downloads> wsl.exe --import test .\test .\ubuntu-22.04-server-cloudimg-amd64-root.tar.xz
Import wird ausgeführt. Dieser Vorgang kann einige Minuten dauern.
Der Vorgang wurde erfolgreich beendet.

PS C:\Users\***\Downloads> wsl -d test

root@***:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       **jammy**

root@***:~# uname -r
5.15.79.1-microsoft-standard-WSL2
```

**Comment by bostrot** [comment]
I was actually playing around with implementing something like this with #75 but did not have the time to finish up :)

With manually importing yes, but at least in my tests (using WSL Manager) with the root.tar.gz files, it would import but create an error when starting one of those distros. I am not 100% sure why this is happening though. (also sometimes it only partly imports tar.gz files which can normally start but are missing some core libraries..)

Also, what is your WSL version (wsl --version)? Might have something to do with that.

**Comment by hedwiggggg** [comment]
> I was actually playing around with implementing something like this with https://github.com/bostrot/wsl2-distro-manager/pull/75 but did not have the time to finish up :)

Nice, #75 seems like a really cool feature; I am curious what may become of it!

> With manually importing yes, but at least in my tests (using WSL Manager) with the root.tar.gz files, it would import but create an error when starting one of those distros. I am not 100% sure why this is happening though. (also sometimes it only partly imports tar.gz files which can normally start but are missing some core libraries..)

That's right, I haven't tried importing via the WSL Manager.

> Also, what is your WSL version (wsl --version)? Might have something to do with that.

```
PS C:\Users\***> wsl --version
WSL-Version: 1.0.3.0
Kernelversion: 5.15.79.1
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22621.1194
```

**Comment by bostrot** [comment]
I guess that didn't work with the version I used before. Weird...

With all the latest versions, importing the rootfs through the WSL Manager works, so I will update that later.
