### ISSUE TITLE
Ability to change default starting directory

### ISSUE THREAD

**Issue by nblain1** [bostrot/wsl2-distro-manager#6]
Upon launching the cli from WSL2 Distro Manager, the starting directory is System 32.  I have edited my JSON file for Windows Terminal to start WSL cli's in /home/%username%, but it doesn't seem to load from the JSON at least.

**Comment by bostrot** [comment]
@nblain1 great idea. Just added this in Release [v0.6.0](https://github.com/bostrot/wsl2-distro-manager/releases/tag/v0.6.0) as a setting. 

![image](https://user-images.githubusercontent.com/7342321/146614976-c2400f55-1cb1-4fec-b590-46c2f451ab59.png)

**Comment by nblain1** [comment]
You are a boss!! Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
