### ISSUE TITLE
Quick Acions

### ISSUE THREAD

**Issue by 2Wdavidcunliffe** [bostrot/wsl2-distro-manager#61]
- No documentation on how to use feature
- Attempts to run quick action in "Ubuntu" only bring up new terminal window but don't action the script

**Comment by bostrot** [comment]
What version + windows version are you using?

**Comment by 2Wdavidcunliffe** [comment]
Sorry for the late response, had issues which delayed my response.

Host OS Version: Windows 11 Home Version 21H2 OS Build 220000.1281 fully patched
WSL Distro Manager Ver: 1.4.2
Guest OS Version: Ubuntu 22.04

**Comment by bostrot** [comment]
Here is a little demo on how it should work. Currently it has the wrong text color so you might need to select the text in the little output to see it. I will change that with the next update.


https://user-images.githubusercontent.com/7342321/204079544-080b0350-b9ba-4b31-bd62-f9da30370ca6.mp4

**Comment by 2Wdavidcunliffe** [comment]
Thanks for reviewing, So when I perform the actions I see that dialog box pop up in your application. I attempted to select the text but it doesn't let me select anything. I tried in both dark mode and light mode. Also when I execute the quick action it opens a new terminal but doesn't seem to be opening the container's terminal up but my PowerShell terminal. I'll try to record the actions and show you. I attempted with my script and just a simple one using the same command in your prior video.

**Comment by bostrot** [comment]
Could you also check which version of WSL you are currently running?

**Comment by 2Wdavidcunliffe** [comment]
wsl --status
Default Version: 2

wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819

**Comment by 2Wdavidcunliffe** [comment]
Pulled down your latest version 1.4.3 and still have the same issues. FYI I was originally using the MS Store option which was on 1.4.2.

**Comment by bostrot** [comment]
I guess I was the one using an outdated WSL version :/ 
Just tested with the latest version and I could reproduce your error:

Seems like Microsoft fixed the "start in detached mode" which the app was still using. I removed that in the quick-actions-fix branch. Could you check if that works for you? (https://github.com/bostrot/wsl2-distro-manager/tree/quick-actions-wsl-fix/build/windows/runner/Release)

**Comment by 2Wdavidcunliffe** [comment]
It works! Where would I find my prior actions located? I lost those during the swaps between versions?

**Comment by bostrot** [comment]
That is weird, do you still have them when you open the MS Store version?

Normally they should be saved in the `%appdata%\com.bostrot\WSL Distro Manager\shared_preferences.json` file. (which needs a change anyways at some point)

**Comment by 2Wdavidcunliffe** [comment]
It's most likely my fault I uninstalled the store version to see if I could get it to update based on the release notification. I guess my code is lost, I'll remember to backup that file in the future. Thanks for addressing the bug.
