### ISSUE TITLE
Missing Docker distros

### ISSUE THREAD

**Issue by sergiirepin** [bostrot/wsl2-distro-manager#77]
**Describe the bug**
Docker distros are not in the list.

**To Reproduce**
1. Install Docker Desktop
2. Enable Integration with default WSL distros in Docker Desktop
3. Run `wsl -l -v` in the console and compare the result with Manager list.

**Expected behavior**
WSL Manager shows  the same list as CLI.

**Screenshots**
![image](https://user-images.githubusercontent.com/3786058/208620177-63f9f0d0-0de3-46e5-8784-c5414193570c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 Pro Insider Preview Build 22000.1335]
 - WSL Manager 1.5.0
 - WSL Version: Kernel version: 5.10.102.1
 - Source [e.g. GitHub releases, GitHub master, Windows Store]

**Comment by bostrot** [comment]
They are hidden on purpose. At least when I started this it made sense. I guess that has to be reevaluated now.

**Comment by sergiirepin** [comment]
@bostrot Thanks!
May be an options which is allow to show system distors.

**Comment by bostrot** [comment]
Yes, I guess that could work. I changed this from bug to feature request for now.
