### ISSUE TITLE
Crashed my PC when creating a new distro

### ISSUE THREAD

**Issue by MarcoBalossini** [bostrot/wsl2-distro-manager#78]
**Describe the bug**
I tryed to create a Ubuntu 20.04 distro on Windows 11.
In the mid of the distro download there was some error I couldn't read, then the screen went black and I had to forcefully restart my PC.

**To Reproduce**
1. Add a distro (Ubuntu 20.04) on a secondary drive

**Expected behavior**
A newly created wsl distro

**Screenshots**
Couldn't take it

**Desktop (please complete the following information):**
 - OS: Windows 11 Education 22H2 Build 22621.963
 - Version 1.5.0
 - WSL Version WSL version: 1.0.3.0
 - Source GitHub releases

**Comment by bostrot** [comment]
Does it still happen if you try it again?

I can not reproduce this issue. Are you sure it comes from the WSL distro manager?

**Comment by MarcoBalossini** [comment]
I will not try again, since I won't crash my system knowingly. But I'm pretty sure it was your program: all other open programs were "well tested" ones I used a thousand times (edge, terminal emulator, vscode, zotero and maybe virtualbox).
When the computer crashed the other programs weren't used, since I was waiting for the creation to finish.
Finally it would seem natural that the fault is of the program giving an error (even though I couldn't read it)

As an additional info: I have plenty of space on both of my drive and I was creating the distro in an empty and newly created directory.

**Comment by bostrot** [comment]
What does it mean that you"couldn't read" the error? Where exactly were you seeing it? 

Also there could be background tasks or other processes that might have caused this crash too. And if you are unwilling to try to test if this happens a second time I unfortunately cannot help you.

**Comment by MarcoBalossini** [comment]
The error was on wsl-distro-manager's window. I left my PC to do it's work and went away for some time, when I got back I barely managed to read the word error (wasn't there before).

I didn't think of background processes, but it was only bitwarden and windows stuff.

Anyway I don't want to be helped since I won't use this program again. I'm just letting you know that there's a problem somewhere.

**Comment by creizlein** [comment]
Omg, what a useless bug report, "screen went blank", "couldnt read the error", "all my other programs are well tested", "I will not try again, my PC might explode and loose all my info".
Dear user, github is not the place for your, nor is reporting a bug, nor playing with Linux, Please open solitarie.exe

There's nothing the author or anyone in here can do with the information you provided.

**Comment by MarcoBalossini** [comment]
Then close the issue and forget it. Don't care. I just thought you should know that there's a serious bug.
Please, at least, have the decency to not bother others with your frustrated deliriums

**Comment by jjlorenzo** [comment]
I can confirm that user another disk, e.g. D: to save distros doesn't work in my machine. The app gets closed immediately.

**Comment by bostrot** [comment]
@jjlorenzo Can you share what Windows version, WSL, etc. you are using?
