### ISSUE TITLE
MSIX installer downloads not available for newest releases on GitHub

### ISSUE THREAD

**Issue by jgstew** [bostrot/wsl2-distro-manager#79]
MSIX installer downloads not available for newest releases on GitHub.

Latest installer is for 1.3.4

**Comment by bostrot** [comment]
That is intented as those have to be signed by microsoft. Otherwise it won't install without installing the certificate first.

**Comment by jgstew** [comment]
I guess that makes sense, though I wish there was an installer available, even if it was a regular MSI or InnoSetup EXE.

**Comment by bostrot** [comment]
At some point, I want to create a CI pipeline to update the winget releases (or chocolatey for that matter) instead of making another installer. Currently, the winget package is outdated (I think v0.5.x) so it can be installed using the following:

    winget install Bostrot.WSLManager

On any modern Windows.

**Comment by bostrot** [comment]
I am closing this for now as I am currently not planning on creating an extra installer.

The winget/chocolatey packages should be enough.

**Comment by bostrot** [comment]
I manually added the signed msix from Microsoft to the release for v1.6.0. I might create a workflow for that at some point to update it.

#42

**Comment by bostrot** [comment]
The workflow now contains a part that adds a self-signed `msix` to the releases. Instructions on how that can be installed can be found in the README.md.

e.g. 

```powershell
Add-AppPackage -Path .\wsl2-distro-manager-v1.6.2-unsigned.msix -AllowUnsigned
```
