### ISSUE TITLE
App crashing when maximizing window

### ISSUE THREAD

**Issue by lasersPew** [bostrot/wsl2-distro-manager#81]
**Describe the bug**
When I maximized the app, it crashes

**To Reproduce**
1. Open app
2. Maximize the app
3. See errors

**Expected behavior**
Maximize the window

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2]
 - Version v0.5.0
 - WSL Version: 1.0.3.0
 - Source:  Github Releases

**Additional context**

**Comment by bostrot** [comment]
What exactly did you do for that to happen? 
I am asking because I cannot replicate that behavior.
