### ISSUE TITLE
[FEATURE] Add support for "real" systemd

### ISSUE THREAD

**Issue by danielk-98** [bostrot/wsl2-distro-manager#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Solution

Hello!

WSL2 now officially supports systemd on some versions. [See here.](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)

It would be great to be able to use systemd on supported WSL2 versions, it just requires an entry to /etc/wsl.conf. And then maybe fallback to "fake systemd" package on unsupported versions.

Great tool, thanks for the hard work!

**Comment by bostrot** [comment]
I will have some more time soon then I will update this. Thanks for reporting!
